#!/bin/bash

##Setup working env
working_dir=/home/iainstott/.conky/Iains_Desktop/
log_file=~/log_file
rm -rf log_file
touch log_file

##Set Ping IP and list
raspi1=192.168.1.1
raspi2=192.168.1.2
raspi3=192.168.1.3
raspi4=192.168.1.4
raspi5=192.168.1.5
raspi6=192.168.0.129
raspiD=192.168.0.130
server=192.168.0.110
ping_ip=(${raspi1} ${raspi2} ${raspi3} ${raspi4} ${raspi5} ${raspi6} ${raspiD} ${server})

##Central Heating 
heating_dir=/home/pi/GitRepo/centralheating
summer=${heating_dir}/resources/summer
status=${heating_dir}/resources/webstatus
manual=${heating_dir}/resources/status


for i in "${ping_ip[@]}"
do
  if ping -c 1 -W 1 $i > /dev/null; then
  echo "On-Line" >> log_file
  else
  echo "Off-Line" >> log_file
  fi
done

ssh pi@${raspi5} "cat ${summer}" >> log_file
ssh pi@${raspi5} "cat ${manual}" >> log_file
ssh pi@${raspi5} "cat ${status}" >> log_file
echo >> log_file
nm-tool |grep --only-matching '*[^ ][^:]*' |sed 's/^*//' >> log_file
/sbin/ifconfig $1 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}' | grep -v '127.0.0.1' >> log_file
wget http://ipinfo.io/ip -qO - >> log_file

killall conky
cd "/home/iainstott/.conky/Iains_Desktop"
conky -c calendar 
conky -c clock 
conky -c local_system"
