#!/bin/bash
TEMPFILE=$1
scp $TEMPFILE pi@192.168.0.131:/home/pi/GitRepo/sketchbook
FILENAME="${TEMPFILE##*/}"
ssh pi@192.168.0.131 'sudo avrdude -p m2560 -C ~/avrdude_gpio.conf -c avrispv2 -P /dev/ttyACM0 -v -U /home/pi/GitRepo/sketchbook/'$FILENAME
